---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: docker
    driver_config:
      box: ubuntu/trusty64

suites:
  - name: registry
    driver:
      network:
      - ['private_network', {ip: '33.33.33.10'}]
    run_list:
      - recipe[mysql-docker-registry::registry]
    attributes:

  - name: mysql
    driver:
      network:
      - ['private_network', {ip: '33.33.33.11'}]
    run_list:
      - recipe[mysql-docker-registry::mysql]
    attributes:
